### ISSUE TITLE
Projections .Net & Redis Sidecar 

### ISSUE THREAD

**Issue by lefig** [Eventuous/connectors#8]
Hi there,

Firstly, I wish to thank your for a fabulous project, great website and series of articles.

Please keep up the good work!!

I think that what would be interesting is understanding how projections could potentially work in practice. All examples that I have found been rather basis and in Javascript. and not C# I am not sure why that is the case. 

A second feature suggestion is to project onto Redis. Although Redis has fabulous streams I don't think that it is as strong as eventstoredb for event sourcing but still a connector would be very beneficial. The simplest way to do this in gRPC is to use Dapr in order to broadcast events to downstream microservices.

Best regards

Fig

**Comment by alexeyzimarev** [comment]
Redis streams sink: #12 
I am not sur about Dapr as I don't think it allows controlling the message format. Dapr expects that messages produced by Dapr sidecar are also consumed by Dapr apps. I haven't spent time looking into it.
